vim.g.mapleader = " "
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set termguicolors")
-- vim.cmd("set verbose=10")
-- vim.cmd("set verbosefile=~/.config/nvim/vim.log")
-- vim.cmd("set foldmethod=indent")
