return {
    "stevearc/aerial.nvim",
    opts = {
        layout = {
            max_width = 0.6,
            placement = "window",
            preserve_equality = true,
        },
        -- manage_folds = true,
        -- link_folds_to_tree = true,
        -- link_tree_to_folds = true,
        attach_mode = "window",
        filter_kind = false,
        --         {
        --             "Array",
        --             "Boolean",
        -- 	"Class",
        -- 	"Constant",
        -- 	"Constructor",
        -- 	"Enum",
        --             "EnumMember",
        --             "Event",
        -- 	"Field",
        --             "File",
        -- 	"Function",
        -- 	"Interface",
        --             "Key",
        -- 	"Method",
        -- 	"Module",
        --             "Namespace",
        --             "Null",
        --             "Number",
        --             "Object",
        --             "Operator",
        -- 	"Package",
        --             "Property",
        --             "String",
        -- 	"Struct",
        --             "TypeParameter",
        --             "Variable",
        -- },
    },
    -- Optional dependencies
    dependencies = {
        "nvim-treesitter/nvim-treesitter",
        "nvim-tree/nvim-web-devicons",
    },
    keys = {
        { "<leader>aa", "<cmd>AerialToggle!<CR>",  mode = "n", desc = "Outline: Toggle" },
        { "<leader>ac", "<cmd>AerialCloseAll<CR>", mode = "n", desc = "Outline: Close all visible aerial windows" },
    },
}
